openapi: '3.0.2'
info:
  title: 'Event and Team API'
  version: '1.0'
paths:
  /new_event:
    post:
      operationId: server.create_event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  type: array
                  items: string
                sport:
                  type: string
                max_users:
                  type: integer
                location:
                  type: string
      responses:
        '201':
          description: Event created successfully
    get:
      operationId: server.get_events
      responses:
        '200':
          description: Success

  /new_team:
    post:
      operationId: server.create__team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  type: array
                  items: string
                team_name:
                  type: string
                location:
                  type: string
                sport:
                  type: string
      responses:
        '201':
          description: Successfully created or joined a team
