openapi: '3.0.2'
info:
  title: 'Sportlink API'
  version: '1.0'

paths:

# account creation endpoint
  /create_account:
    post:
      operationId: app.create_account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
        '401':
          description: Email already has an account!
  /update_profile:
    post:
      operationId: app.update_user_profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    username:
                      type: string
                phoneNumber:
                  type: string
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
