openapi: '3.0.2'
info:
  title: 'Sportlink API'
  version: '1.0'

paths:

# account creation endpoint
  /create_account:
    post:
      operationId: app.create_account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
        '401':
          description: Email already has an account!

  /google_signin:
    post:
      operationId: app.google_signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                googleId:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '201':
          description: Google User Account Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
        '200':
          description: Google User Login
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  phoneNumber:
                    type: string
                  friends:  
                    type: array
                    items:
                      type: string
                required:
                  - username
        '401':
          description: Incorrect email or password!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string


#login endpoint
  /login:
      post:
        operationId: app.login
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
        responses:
          '200':
            description: User logged in
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    email:
                      type: string
                    username:
                      type: string  
                    firstName:
                      type: string
                    lastName:
                      type: string
                    phoneNumber:
                      type: string
                    friends:
                      type: array
                      items:
                        type: string
                  required:
                    - email
                    - username       
          '401':
            description: Incorrect email or password!
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error: 
                      type: string  

  /get_token:
    post:
      operationId: app.get_token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password Reset email sent!
        '401':
          description: Email does not exist!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string

  /input_reset_token:
    post:
      operationId: app.input_reset_token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                reqToken:
                  type: string
      responses:
        '200':
          description: Password Token Verified!
        '401':
          description: Incorrect token!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string

  /change_user_password:
    post:
      operationId: app.change_password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Password Changed!
        '401':
          description: Error!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string

  /update_profile:
    post:
      operationId: app.update_user_profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phoneNumber:
                  type: string
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
